export type ExerciseCategory =
  | 'Chest'
  | 'Back'
  | 'Shoulders'
  | 'Quads'
  | 'Hamstrings'
  | 'Glutes'
  | 'Calves'
  | 'Biceps'
  | 'Triceps'
  | 'Core'
  | 'Cardio'
  | 'Mobility';

export type ExerciseEquipment =
  | 'Barbell'
  | 'Dumbbell'
  | 'Cable'
  | 'Machine'
  | 'Bodyweight'
  | 'Kettlebell'
  | 'Cardio Equipment'
  | 'Bands / Other';

export type ExerciseKind = 'strength' | 'cardio' | 'flexibility';

export interface ExerciseDefinition {
  id: string;
  name: string;
  category: ExerciseCategory;
  equipment: ExerciseEquipment;
  kind: ExerciseKind;
  primaryMuscle: string;
  defaultSets: number;
  defaultReps: string;
  defaultMinutes?: number;
  attribute: 'STR' | 'VIT' | 'AGI' | 'PER' | 'INT';
  cue?: string;
}

export const EXERCISE_CATEGORIES: ExerciseCategory[] = [
  'Chest',
  'Back',
  'Shoulders',
  'Quads',
  'Hamstrings',
  'Glutes',
  'Calves',
  'Biceps',
  'Triceps',
  'Core',
  'Cardio',
  'Mobility',
];

export const EXERCISE_EQUIPMENTS: ExerciseEquipment[] = [
  'Barbell',
  'Dumbbell',
  'Cable',
  'Machine',
  'Bodyweight',
  'Kettlebell',
  'Cardio Equipment',
  'Bands / Other',
];

export const EXERCISE_LIBRARY: ExerciseDefinition[] = [
  // ──────────────────────────── CHEST ────────────────────────────
  {
    id: 'barbell-bench-press',
    name: 'Barbell Flat Bench Press',
    category: 'Chest',
    equipment: 'Barbell',
    kind: 'strength',
    primaryMuscle: 'Pectoralis Major',
    defaultSets: 4,
    defaultReps: '6-8',
    attribute: 'STR',
    cue: 'Retract scapula, arch slightly, drive through heels.',
  },
  {
    id: 'incline-dumbbell-press',
    name: 'Incline Dumbbell Bench Press',
    category: 'Chest',
    equipment: 'Dumbbell',
    kind: 'strength',
    primaryMuscle: 'Upper Chest (Clavicular Head)',
    defaultSets: 3,
    defaultReps: '8-10',
    attribute: 'STR',
    cue: 'Set bench to 30°, tuck elbows at 45° angle.',
  },
  {
    id: 'flat-dumbbell-press',
    name: 'Flat Dumbbell Press',
    category: 'Chest',
    equipment: 'Dumbbell',
    kind: 'strength',
    primaryMuscle: 'Mid Pectorals',
    defaultSets: 3,
    defaultReps: '8-12',
    attribute: 'STR',
    cue: 'Full stretch at bottom, squeeze dumbbells together at peak.',
  },
  {
    id: 'incline-barbell-bench',
    name: 'Incline Barbell Bench Press',
    category: 'Chest',
    equipment: 'Barbell',
    kind: 'strength',
    primaryMuscle: 'Upper Chest',
    defaultSets: 3,
    defaultReps: '6-8',
    attribute: 'STR',
    cue: 'Lower bar smoothly to upper chest clavicle line.',
  },
  {
    id: 'chest-dips',
    name: 'Weighted Chest Dips',
    category: 'Chest',
    equipment: 'Bodyweight',
    kind: 'strength',
    primaryMuscle: 'Lower Chest & Triceps',
    defaultSets: 3,
    defaultReps: '8-12',
    attribute: 'STR',
    cue: 'Lean torso forward 30° to bias chest over triceps.',
  },
  {
    id: 'cable-chest-flyes-high',
    name: 'Cable Flyes (High to Low)',
    category: 'Chest',
    equipment: 'Cable',
    kind: 'strength',
    primaryMuscle: 'Lower / Mid Chest',
    defaultSets: 3,
    defaultReps: '12-15',
    attribute: 'STR',
    cue: 'Hug a barrel movement, maintain soft elbow bend.',
  },
  {
    id: 'cable-chest-flyes-low',
    name: 'Cable Flyes (Low to High)',
    category: 'Chest',
    equipment: 'Cable',
    kind: 'strength',
    primaryMuscle: 'Upper Chest',
    defaultSets: 3,
    defaultReps: '12-15',
    attribute: 'STR',
    cue: 'Drive hands up toward eye level with controlled tempo.',
  },
  {
    id: 'pec-deck-machine',
    name: 'Pec Deck Machine Flyes',
    category: 'Chest',
    equipment: 'Machine',
    kind: 'strength',
    primaryMuscle: 'Sternal Pectorals',
    defaultSets: 3,
    defaultReps: '10-12',
    attribute: 'STR',
    cue: 'Keep chest proud and elbows slightly bent.',
  },
  {
    id: 'machine-chest-press',
    name: 'Seated Machine Chest Press',
    category: 'Chest',
    equipment: 'Machine',
    kind: 'strength',
    primaryMuscle: 'Pectoralis Major',
    defaultSets: 3,
    defaultReps: '10-12',
    attribute: 'STR',
    cue: 'Consistent tension with no lockout at top.',
  },
  {
    id: 'push-ups-standard',
    name: 'Push-Ups (Standard / Deficit)',
    category: 'Chest',
    equipment: 'Bodyweight',
    kind: 'strength',
    primaryMuscle: 'Chest & Core',
    defaultSets: 3,
    defaultReps: '15-20',
    attribute: 'STR',
    cue: 'Maintain plank posture, touch chest to floor.',
  },
  {
    id: 'decline-barbell-press',
    name: 'Decline Barbell Press',
    category: 'Chest',
    equipment: 'Barbell',
    kind: 'strength',
    primaryMuscle: 'Lower Pectorals',
    defaultSets: 3,
    defaultReps: '8-10',
    attribute: 'STR',
  },
  {
    id: 'dumbbell-pullover',
    name: 'Dumbbell Pullover',
    category: 'Chest',
    equipment: 'Dumbbell',
    kind: 'strength',
    primaryMuscle: 'Chest & Serratus Anterior',
    defaultSets: 3,
    defaultReps: '10-12',
    attribute: 'STR',
  },
  {
    id: 'landmine-press',
    name: 'Landmine Chest Press',
    category: 'Chest',
    equipment: 'Barbell',
    kind: 'strength',
    primaryMuscle: 'Upper Chest & Front Delts',
    defaultSets: 3,
    defaultReps: '10-12',
    attribute: 'STR',
  },

  // ──────────────────────────── BACK ────────────────────────────
  {
    id: 'deadlift-conventional',
    name: 'Conventional Barbell Deadlift',
    category: 'Back',
    equipment: 'Barbell',
    kind: 'strength',
    primaryMuscle: 'Erector Spinae & Posterior Chain',
    defaultSets: 4,
    defaultReps: '5',
    attribute: 'STR',
    cue: 'Pack lats, push floor away through mid-foot.',
  },
  {
    id: 'barbell-bent-over-row',
    name: 'Barbell Bent-Over Row',
    category: 'Back',
    equipment: 'Barbell',
    kind: 'strength',
    primaryMuscle: 'Latissimus Dorsi & Rhomboids',
    defaultSets: 4,
    defaultReps: '6-8',
    attribute: 'STR',
    cue: 'Hinge at hips at 45°, pull bar toward belly button.',
  },
  {
    id: 'lat-pulldown-wide',
    name: 'Wide-Grip Lat Pulldown',
    category: 'Back',
    equipment: 'Cable',
    kind: 'strength',
    primaryMuscle: 'Latissimus Dorsi',
    defaultSets: 3,
    defaultReps: '8-12',
    attribute: 'STR',
    cue: 'Initiate by depressing scapula, pull to clavicle.',
  },
  {
    id: 'weighted-pull-ups',
    name: 'Pull-Ups (Bodyweight or Weighted)',
    category: 'Back',
    equipment: 'Bodyweight',
    kind: 'strength',
    primaryMuscle: 'Lats & Upper Back',
    defaultSets: 3,
    defaultReps: '6-10',
    attribute: 'STR',
    cue: 'Chest up, clear chin over bar without swinging.',
  },
  {
    id: 'chin-ups',
    name: 'Chin-Ups (Underhand Grip)',
    category: 'Back',
    equipment: 'Bodyweight',
    kind: 'strength',
    primaryMuscle: 'Lats & Biceps',
    defaultSets: 3,
    defaultReps: '8-10',
    attribute: 'STR',
  },
  {
    id: 'seated-cable-row',
    name: 'Seated Cable Row (Close Grip)',
    category: 'Back',
    equipment: 'Cable',
    kind: 'strength',
    primaryMuscle: 'Mid Back & Rhomboids',
    defaultSets: 3,
    defaultReps: '10-12',
    attribute: 'STR',
    cue: 'Keep chest upright, squeeze shoulder blades back.',
  },
  {
    id: 't-bar-row',
    name: 'T-Bar Row (Chest-Supported or Free)',
    category: 'Back',
    equipment: 'Machine',
    kind: 'strength',
    primaryMuscle: 'Middle Trapezius & Lats',
    defaultSets: 3,
    defaultReps: '8-10',
    attribute: 'STR',
  },
  {
    id: 'single-arm-dumbbell-row',
    name: 'Single-Arm Dumbbell Row',
    category: 'Back',
    equipment: 'Dumbbell',
    kind: 'strength',
    primaryMuscle: 'Latissimus Dorsi',
    defaultSets: 3,
    defaultReps: '10-12',
    attribute: 'STR',
    cue: 'Pull elbow toward hip pocket with zero torso twist.',
  },
  {
    id: 'cable-face-pulls',
    name: 'Cable Face Pulls (Rear Delts / Traps)',
    category: 'Back',
    equipment: 'Cable',
    kind: 'strength',
    primaryMuscle: 'Rear Delts & Rhomboids',
    defaultSets: 3,
    defaultReps: '12-15',
    attribute: 'VIT',
    cue: 'Pull rope toward forehead, rotate hands outward.',
  },
  {
    id: 'straight-arm-pulldown',
    name: 'Cable Straight-Arm Lat Pulldown',
    category: 'Back',
    equipment: 'Cable',
    kind: 'strength',
    primaryMuscle: 'Lats & Teres Major',
    defaultSets: 3,
    defaultReps: '12-15',
    attribute: 'STR',
  },
  {
    id: 'barbell-shrugs',
    name: 'Barbell / Dumbbell Shrugs',
    category: 'Back',
    equipment: 'Barbell',
    kind: 'strength',
    primaryMuscle: 'Upper Trapezius',
    defaultSets: 3,
    defaultReps: '12-15',
    attribute: 'STR',
  },
  {
    id: 'rack-pulls',
    name: 'Rack Pulls (Above Knee)',
    category: 'Back',
    equipment: 'Barbell',
    kind: 'strength',
    primaryMuscle: 'Traps & Spinal Erectors',
    defaultSets: 3,
    defaultReps: '5-8',
    attribute: 'STR',
  },
  {
    id: 'back-hyperextension',
    name: '45° Back Hyperextension',
    category: 'Back',
    equipment: 'Machine',
    kind: 'strength',
    primaryMuscle: 'Lower Back & Hamstrings',
    defaultSets: 3,
    defaultReps: '12-15',
    attribute: 'VIT',
  },

  // ──────────────────────────── SHOULDERS ────────────────────────────
  {
    id: 'overhead-barbell-press',
    name: 'Standing Overhead Barbell Press (OHP)',
    category: 'Shoulders',
    equipment: 'Barbell',
    kind: 'strength',
    primaryMuscle: 'Anterior & Lateral Deltoids',
    defaultSets: 4,
    defaultReps: '6-8',
    attribute: 'STR',
    cue: 'Glutes clenched, lock out overhead with head pushed through.',
  },
  {
    id: 'seated-dumbbell-shoulder-press',
    name: 'Seated Dumbbell Shoulder Press',
    category: 'Shoulders',
    equipment: 'Dumbbell',
    kind: 'strength',
    primaryMuscle: 'Anterior & Medial Delts',
    defaultSets: 3,
    defaultReps: '8-10',
    attribute: 'STR',
    cue: 'Lower dumbbells until level with ears, press up in slight arc.',
  },
  {
    id: 'standing-dumbbell-lateral-raise',
    name: 'Dumbbell Lateral Raises',
    category: 'Shoulders',
    equipment: 'Dumbbell',
    kind: 'strength',
    primaryMuscle: 'Lateral Deltoids',
    defaultSets: 4,
    defaultReps: '12-15',
    attribute: 'STR',
    cue: 'Lead with elbows, slight forward lean, control eccentric.',
  },
  {
    id: 'cable-lateral-raise',
    name: 'Cable Lateral Raise',
    category: 'Shoulders',
    equipment: 'Cable',
    kind: 'strength',
    primaryMuscle: 'Lateral Deltoids',
    defaultSets: 3,
    defaultReps: '12-15',
    attribute: 'STR',
    cue: 'Constant tension throughout entire range of motion.',
  },
  {
    id: 'arnold-press',
    name: 'Arnold Dumbbell Press',
    category: 'Shoulders',
    equipment: 'Dumbbell',
    kind: 'strength',
    primaryMuscle: 'Full Deltoid Complex',
    defaultSets: 3,
    defaultReps: '10-12',
    attribute: 'STR',
    cue: 'Rotate palms smoothly from facing you to facing outward.',
  },
  {
    id: 'rear-delt-pec-deck',
    name: 'Reverse Pec Deck (Rear Delts)',
    category: 'Shoulders',
    equipment: 'Machine',
    kind: 'strength',
    primaryMuscle: 'Posterior Deltoids',
    defaultSets: 3,
    defaultReps: '12-15',
    attribute: 'STR',
    cue: 'Keep wrists relaxed, pull through rear delts.',
  },
  {
    id: 'rear-delt-dumbbell-fly',
    name: 'Bent-Over Rear Delt DB Flyes',
    category: 'Shoulders',
    equipment: 'Dumbbell',
    kind: 'strength',
    primaryMuscle: 'Posterior Deltoids',
    defaultSets: 3,
    defaultReps: '12-15',
    attribute: 'STR',
  },
  {
    id: 'dumbbell-front-raise',
    name: 'Dumbbell Front Raises',
    category: 'Shoulders',
    equipment: 'Dumbbell',
    kind: 'strength',
    primaryMuscle: 'Anterior Deltoid',
    defaultSets: 3,
    defaultReps: '10-12',
    attribute: 'STR',
  },
  {
    id: 'upright-row',
    name: 'Cable / Barbell Upright Row',
    category: 'Shoulders',
    equipment: 'Cable',
    kind: 'strength',
    primaryMuscle: 'Lateral Deltoids & Traps',
    defaultSets: 3,
    defaultReps: '10-12',
    attribute: 'STR',
  },
  {
    id: 'machine-shoulder-press',
    name: 'Machine Overhead Press',
    category: 'Shoulders',
    equipment: 'Machine',
    kind: 'strength',
    primaryMuscle: 'Deltoids',
    defaultSets: 3,
    defaultReps: '10-12',
    attribute: 'STR',
  },

  // ──────────────────────────── QUADS ────────────────────────────
  {
    id: 'barbell-back-squat',
    name: 'Barbell Back Squat',
    category: 'Quads',
    equipment: 'Barbell',
    kind: 'strength',
    primaryMuscle: 'Quadriceps & Glutes',
    defaultSets: 4,
    defaultReps: '5-8',
    attribute: 'STR',
    cue: 'Knees track over toes, break parallel, drive hips up.',
  },
  {
    id: 'barbell-front-squat',
    name: 'Barbell Front Squat',
    category: 'Quads',
    equipment: 'Barbell',
    kind: 'strength',
    primaryMuscle: 'Quadriceps & Core',
    defaultSets: 3,
    defaultReps: '6-8',
    attribute: 'STR',
    cue: 'Elbows high, torso upright, deep quad recruitment.',
  },
  {
    id: 'leg-press-45',
    name: '45° Leg Press',
    category: 'Quads',
    equipment: 'Machine',
    kind: 'strength',
    primaryMuscle: 'Quadriceps',
    defaultSets: 4,
    defaultReps: '10-12',
    attribute: 'STR',
    cue: 'Do not lock out knees at top, lower to 90° knee flexion.',
  },
  {
    id: 'hack-squat',
    name: 'Hack Squat (Machine)',
    category: 'Quads',
    equipment: 'Machine',
    kind: 'strength',
    primaryMuscle: 'Quadriceps',
    defaultSets: 3,
    defaultReps: '8-10',
    attribute: 'STR',
    cue: 'Foot placement low and shoulder-width for maximum quad focus.',
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squats (Dumbbell)',
    category: 'Quads',
    equipment: 'Dumbbell',
    kind: 'strength',
    primaryMuscle: 'Quads & Glutes',
    defaultSets: 3,
    defaultReps: '8-10/leg',
    attribute: 'STR',
    cue: 'Rear foot elevated, sink hips down and slightly back.',
  },
  {
    id: 'walking-lunges',
    name: 'Walking Dumbbell Lunges',
    category: 'Quads',
    equipment: 'Dumbbell',
    kind: 'strength',
    primaryMuscle: 'Quads & Glute Medius',
    defaultSets: 3,
    defaultReps: '10-12/leg',
    attribute: 'STR',
  },
  {
    id: 'leg-extensions',
    name: 'Seated Leg Extensions',
    category: 'Quads',
    equipment: 'Machine',
    kind: 'strength',
    primaryMuscle: 'Rectus Femoris & Vastus Lateralis',
    defaultSets: 3,
    defaultReps: '12-15',
    attribute: 'STR',
    cue: 'Pause 1s at top contraction, slow 3s eccentric descent.',
  },
  {
    id: 'goblet-squats',
    name: 'Goblet Squats (Kettlebell/DB)',
    category: 'Quads',
    equipment: 'Kettlebell',
    kind: 'strength',
    primaryMuscle: 'Quads & Core',
    defaultSets: 3,
    defaultReps: '12-15',
    attribute: 'STR',
  },
  {
    id: 'sissy-squats',
    name: 'Sissy Squats (Bodyweight / Machine)',
    category: 'Quads',
    equipment: 'Bodyweight',
    kind: 'strength',
    primaryMuscle: 'Isolated Quads',
    defaultSets: 3,
    defaultReps: '10-12',
    attribute: 'STR',
  },

  // ──────────────────────────── HAMSTRINGS & GLUTES ────────────────────────────
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift (RDL - Barbell)',
    category: 'Hamstrings',
    equipment: 'Barbell',
    kind: 'strength',
    primaryMuscle: 'Hamstrings & Gluteus Maximus',
    defaultSets: 3,
    defaultReps: '8-10',
    attribute: 'STR',
    cue: 'Soft knees, push hips back to wall until deep hamstring stretch.',
  },
  {
    id: 'dumbbell-rdl',
    name: 'Dumbbell Romanian Deadlift',
    category: 'Hamstrings',
    equipment: 'Dumbbell',
    kind: 'strength',
    primaryMuscle: 'Hamstrings',
    defaultSets: 3,
    defaultReps: '10-12',
    attribute: 'STR',
  },
  {
    id: 'barbell-hip-thrust',
    name: 'Barbell Hip Thrust',
    category: 'Glutes',
    equipment: 'Barbell',
    kind: 'strength',
    primaryMuscle: 'Gluteus Maximus',
    defaultSets: 4,
    defaultReps: '8-12',
    attribute: 'STR',
    cue: 'Chin tucked, full hip extension at top with glute squeeze.',
  },
  {
    id: 'lying-leg-curl',
    name: 'Lying Hamstring Leg Curls',
    category: 'Hamstrings',
    equipment: 'Machine',
    kind: 'strength',
    primaryMuscle: 'Biceps Femoris',
    defaultSets: 3,
    defaultReps: '10-12',
    attribute: 'STR',
    cue: 'Keep hips pressed into pad, no hyperextension.',
  },
  {
    id: 'seated-leg-curl',
    name: 'Seated Hamstring Leg Curls',
    category: 'Hamstrings',
    equipment: 'Machine',
    kind: 'strength',
    primaryMuscle: 'Hamstrings Complex',
    defaultSets: 3,
    defaultReps: '10-12',
    attribute: 'STR',
    cue: 'Superior stretch position; control negative.',
  },
  {
    id: 'standing-calf-raises',
    name: 'Standing Calf Raises (Machine / Smith)',
    category: 'Calves',
    equipment: 'Machine',
    kind: 'strength',
    primaryMuscle: 'Gastrocnemius',
    defaultSets: 4,
    defaultReps: '12-15',
    attribute: 'AGI',
    cue: 'Deep stretch at bottom, explosive rise onto balls of feet.',
  },
  {
    id: 'seated-calf-raises',
    name: 'Seated Calf Raises',
    category: 'Calves',
    equipment: 'Machine',
    kind: 'strength',
    primaryMuscle: 'Soleus',
    defaultSets: 3,
    defaultReps: '15-20',
    attribute: 'AGI',
  },

  // ──────────────────────────── ARMS: BICEPS ────────────────────────────
  {
    id: 'barbell-bicep-curl',
    name: 'Barbell / EZ-Bar Bicep Curl',
    category: 'Biceps',
    equipment: 'Barbell',
    kind: 'strength',
    primaryMuscle: 'Biceps Brachii',
    defaultSets: 3,
    defaultReps: '8-10',
    attribute: 'STR',
    cue: 'Pin elbows to sides, curl without swinging hips.',
  },
  {
    id: 'incline-dumbbell-curl',
    name: 'Incline Dumbbell Bicep Curl',
    category: 'Biceps',
    equipment: 'Dumbbell',
    kind: 'strength',
    primaryMuscle: 'Biceps Long Head',
    defaultSets: 3,
    defaultReps: '10-12',
    attribute: 'STR',
    cue: 'Bench at 45°, maximum long-head stretch.',
  },
  {
    id: 'dumbbell-hammer-curl',
    name: 'Dumbbell Hammer Curls',
    category: 'Biceps',
    equipment: 'Dumbbell',
    kind: 'strength',
    primaryMuscle: 'Brachialis & Brachioradialis',
    defaultSets: 3,
    defaultReps: '10-12',
    attribute: 'STR',
    cue: 'Neutral grip (palms facing each other), builds forearm thickness.',
  },
  {
    id: 'preacher-curl',
    name: 'Preacher Curl (EZ Bar / Dumbbell)',
    category: 'Biceps',
    equipment: 'Barbell',
    kind: 'strength',
    primaryMuscle: 'Biceps Short Head',
    defaultSets: 3,
    defaultReps: '10-12',
    attribute: 'STR',
    cue: 'No cheating momentum, full contraction.',
  },
  {
    id: 'cable-rope-bicep-curl',
    name: 'Cable Bicep Curls (Rope / Bar)',
    category: 'Biceps',
    equipment: 'Cable',
    kind: 'strength',
    primaryMuscle: 'Biceps Brachii',
    defaultSets: 3,
    defaultReps: '12-15',
    attribute: 'STR',
  },
  {
    id: 'spider-curls',
    name: 'Spider Curls (Incline Bench)',
    category: 'Biceps',
    equipment: 'Dumbbell',
    kind: 'strength',
    primaryMuscle: 'Biceps Short Head Peak',
    defaultSets: 3,
    defaultReps: '10-12',
    attribute: 'STR',
  },
  {
    id: 'concentration-curls',
    name: 'Concentration Curls',
    category: 'Biceps',
    equipment: 'Dumbbell',
    kind: 'strength',
    primaryMuscle: 'Biceps Peak',
    defaultSets: 3,
    defaultReps: '12-15',
    attribute: 'STR',
  },

  // ──────────────────────────── ARMS: TRICEPS ────────────────────────────
  {
    id: 'cable-tricep-pushdown',
    name: 'Cable Rope Tricep Pushdown',
    category: 'Triceps',
    equipment: 'Cable',
    kind: 'strength',
    primaryMuscle: 'Triceps Lateral Head',
    defaultSets: 3,
    defaultReps: '10-12',
    attribute: 'STR',
    cue: 'Flare rope outward at bottom, lock out triceps.',
  },
  {
    id: 'skull-crushers',
    name: 'EZ-Bar Skull Crushers (Lying Extension)',
    category: 'Triceps',
    equipment: 'Barbell',
    kind: 'strength',
    primaryMuscle: 'Triceps Medial & Long Head',
    defaultSets: 3,
    defaultReps: '8-10',
    attribute: 'STR',
    cue: 'Lower bar toward forehead/crown, elbows tucked.',
  },
  {
    id: 'overhead-dumbbell-tricep',
    name: 'Overhead Dumbbell Tricep Extension',
    category: 'Triceps',
    equipment: 'Dumbbell',
    kind: 'strength',
    primaryMuscle: 'Triceps Long Head',
    defaultSets: 3,
    defaultReps: '10-12',
    attribute: 'STR',
    cue: 'Deep stretch behind neck, flare elbows slightly.',
  },
  {
    id: 'close-grip-bench-press',
    name: 'Close-Grip Barbell Bench Press',
    category: 'Triceps',
    equipment: 'Barbell',
    kind: 'strength',
    primaryMuscle: 'Triceps & Inner Chest',
    defaultSets: 3,
    defaultReps: '6-8',
    attribute: 'STR',
    cue: 'Hands shoulder-width apart, elbows graze ribs.',
  },
  {
    id: 'parallel-bar-dips-tricep',
    name: 'Parallel Bar Dips (Tricep Focus)',
    category: 'Triceps',
    equipment: 'Bodyweight',
    kind: 'strength',
    primaryMuscle: 'Triceps Brachii',
    defaultSets: 3,
    defaultReps: '10-12',
    attribute: 'STR',
    cue: 'Stay upright to isolate triceps.',
  },
  {
    id: 'cable-overhead-extension',
    name: 'Cable Overhead Tricep Extension',
    category: 'Triceps',
    equipment: 'Cable',
    kind: 'strength',
    primaryMuscle: 'Triceps Long Head',
    defaultSets: 3,
    defaultReps: '12-15',
    attribute: 'STR',
  },

  // ──────────────────────────── CORE ────────────────────────────
  {
    id: 'hanging-leg-raises',
    name: 'Hanging Leg Raises / Knee Tucks',
    category: 'Core',
    equipment: 'Bodyweight',
    kind: 'strength',
    primaryMuscle: 'Rectus Abdominis (Lower) & Hip Flexors',
    defaultSets: 3,
    defaultReps: '12-15',
    attribute: 'VIT',
    cue: 'Posterior pelvic tilt, curl pelvis up toward ribs.',
  },
  {
    id: 'ab-wheel-rollout',
    name: 'Ab Wheel Rollout',
    category: 'Core',
    equipment: 'Bodyweight',
    kind: 'strength',
    primaryMuscle: 'Core Anterior Chain',
    defaultSets: 3,
    defaultReps: '8-12',
    attribute: 'VIT',
    cue: 'Do not sag lower back; stay hollow.',
  },
  {
    id: 'cable-woodchoppers',
    name: 'Cable Woodchoppers',
    category: 'Core',
    equipment: 'Cable',
    kind: 'strength',
    primaryMuscle: 'Obliques & Transverse Abdominis',
    defaultSets: 3,
    defaultReps: '12-15/side',
    attribute: 'AGI',
  },
  {
    id: 'kneeling-cable-crunch',
    name: 'Kneeling Cable Crunch',
    category: 'Core',
    equipment: 'Cable',
    kind: 'strength',
    primaryMuscle: 'Upper Rectus Abdominis',
    defaultSets: 3,
    defaultReps: '12-15',
    attribute: 'VIT',
    cue: 'Round spine to pull elbows toward knees with abs.',
  },
  {
    id: 'weighted-plank',
    name: 'Plank Hold (Standard or Weighted)',
    category: 'Core',
    equipment: 'Bodyweight',
    kind: 'strength',
    primaryMuscle: 'Transverse Abdominis',
    defaultSets: 3,
    defaultReps: '60s hold',
    attribute: 'VIT',
  },
  {
    id: 'russian-twists',
    name: 'Russian Twists (Plate / Medicine Ball)',
    category: 'Core',
    equipment: 'Dumbbell',
    kind: 'strength',
    primaryMuscle: 'Obliques',
    defaultSets: 3,
    defaultReps: '20 total',
    attribute: 'AGI',
  },
  {
    id: 'dragon-flags',
    name: 'Dragon Flags (Bruce Lee Ab Protocol)',
    category: 'Core',
    equipment: 'Bodyweight',
    kind: 'strength',
    primaryMuscle: 'Entire Core Wall',
    defaultSets: 3,
    defaultReps: '5-8',
    attribute: 'STR',
  },

  // ──────────────────────────── CARDIO & CONDITIONING ────────────────────────────
  {
    id: 'running-outdoor',
    name: 'Outdoor Run / Jog (3-5 km)',
    category: 'Cardio',
    equipment: 'Bodyweight',
    kind: 'cardio',
    primaryMuscle: 'Cardiovascular & Lower Body',
    defaultSets: 1,
    defaultReps: '30 min',
    defaultMinutes: 30,
    attribute: 'VIT',
    cue: 'Maintain Zone 2 steady state or tempo pace.',
  },
  {
    id: 'treadmill-incline-walk',
    name: '12-3-30 Incline Treadmill Walk',
    category: 'Cardio',
    equipment: 'Cardio Equipment',
    kind: 'cardio',
    primaryMuscle: 'Cardiovascular & Glutes/Calves',
    defaultSets: 1,
    defaultReps: '30 min',
    defaultMinutes: 30,
    attribute: 'VIT',
    cue: '12% incline, 3 mph, 30 minutes. Low impact fat burn.',
  },
  {
    id: 'rowing-machine-erg',
    name: 'Rowing Machine Ergometer (500m Intervals)',
    category: 'Cardio',
    equipment: 'Cardio Equipment',
    kind: 'cardio',
    primaryMuscle: 'Full Body Endurance',
    defaultSets: 4,
    defaultReps: '500m sprint',
    defaultMinutes: 20,
    attribute: 'VIT',
  },
  {
    id: 'jump-rope-conditioning',
    name: 'Jump Rope High-Cadence Intervals',
    category: 'Cardio',
    equipment: 'Bodyweight',
    kind: 'cardio',
    primaryMuscle: 'Calves & Foot Agility',
    defaultSets: 5,
    defaultReps: '3 min rounds',
    defaultMinutes: 15,
    attribute: 'AGI',
  },
  {
    id: 'assault-bike-sprints',
    name: 'Assault / Air Bike Death Sprints',
    category: 'Cardio',
    equipment: 'Cardio Equipment',
    kind: 'cardio',
    primaryMuscle: 'Anaerobic Capacity',
    defaultSets: 6,
    defaultReps: '30s sprint / 60s rest',
    defaultMinutes: 15,
    attribute: 'VIT',
  },
  {
    id: 'stairmaster-climb',
    name: 'Stairmaster Gauntlet Climb',
    category: 'Cardio',
    equipment: 'Cardio Equipment',
    kind: 'cardio',
    primaryMuscle: 'Glutes, Quads & Heart',
    defaultSets: 1,
    defaultReps: '25 min',
    defaultMinutes: 25,
    attribute: 'VIT',
  },
  {
    id: 'swimming-laps',
    name: 'Freestyle Swimming Laps',
    category: 'Cardio',
    equipment: 'Bodyweight',
    kind: 'cardio',
    primaryMuscle: 'Lats, Shoulders & Cardio',
    defaultSets: 1,
    defaultReps: '1000m',
    defaultMinutes: 30,
    attribute: 'VIT',
  },
  {
    id: 'kettlebell-swings',
    name: 'Kettlebell Swings (Russian / American)',
    category: 'Cardio',
    equipment: 'Kettlebell',
    kind: 'strength',
    primaryMuscle: 'Posterior Chain & Cardio',
    defaultSets: 4,
    defaultReps: '20',
    attribute: 'STR',
  },
  {
    id: 'farmers-walk',
    name: "Farmer's Walk (Heavy Carry)",
    category: 'Cardio',
    equipment: 'Dumbbell',
    kind: 'strength',
    primaryMuscle: 'Grip, Traps & Core',
    defaultSets: 3,
    defaultReps: '40 meters',
    attribute: 'STR',
    cue: 'Walk with tall posture and crushing grip.',
  },

  // ──────────────────────────── MOBILITY & RECOVERY ────────────────────────────
  {
    id: 'deep-squat-hold',
    name: 'Deep Squat Hold & Hip Prying',
    category: 'Mobility',
    equipment: 'Bodyweight',
    kind: 'flexibility',
    primaryMuscle: 'Hip Flexors, Ankles & Adductors',
    defaultSets: 3,
    defaultReps: '60s hold',
    defaultMinutes: 10,
    attribute: 'AGI',
  },
  {
    id: 'worlds-greatest-stretch',
    name: "World's Greatest Stretch Flow",
    category: 'Mobility',
    equipment: 'Bodyweight',
    kind: 'flexibility',
    primaryMuscle: 'Hips, Thoracic Spine & Hamstrings',
    defaultSets: 2,
    defaultReps: '6/side',
    defaultMinutes: 10,
    attribute: 'AGI',
  },
  {
    id: 'foam-rolling-full',
    name: 'Full Body Foam Rolling & Myofascial Release',
    category: 'Mobility',
    equipment: 'Bands / Other',
    kind: 'flexibility',
    primaryMuscle: 'IT Band, Quads, Back & Calves',
    defaultSets: 1,
    defaultReps: '15 min',
    defaultMinutes: 15,
    attribute: 'VIT',
  },
  {
    id: 'dead-hang',
    name: 'Dead Hang (Spinal Decompression & Grip)',
    category: 'Mobility',
    equipment: 'Bodyweight',
    kind: 'flexibility',
    primaryMuscle: 'Shoulder Capsule, Lats & Spine',
    defaultSets: 3,
    defaultReps: '45-60s hold',
    defaultMinutes: 5,
    attribute: 'VIT',
    cue: 'Relax shoulders and let gravity decompress vertebrae.',
  },
];

export interface PresetSplitTemplate {
  id: string;
  name: string;
  description: string;
  daysPerWeek: number;
  level: 'Beginner' | 'Intermediate' | 'Advanced';
  tags: string[];
  schedule: Record<
    number,
    {
      focus: string;
      isRestDay: boolean;
      exerciseIds: string[];
    }
  >;
}

export const PRESET_SPLIT_TEMPLATES: PresetSplitTemplate[] = [
  {
    id: 'ppl-6day',
    name: 'Push / Pull / Legs (Hypertrophy & Strength)',
    description:
      'The gold standard Hunter training split. High volume, balanced muscle growth with maximum recovery spacing.',
    daysPerWeek: 6,
    level: 'Intermediate',
    tags: ['Gym', 'Hypertrophy', 'Aesthetic', 'Popular'],
    schedule: {
      1: {
        // Monday
        focus: 'Push (Chest, Shoulders, Triceps)',
        isRestDay: false,
        exerciseIds: [
          'barbell-bench-press',
          'incline-dumbbell-press',
          'standing-dumbbell-lateral-raise',
          'cable-tricep-pushdown',
          'overhead-dumbbell-tricep',
        ],
      },
      2: {
        // Tuesday
        focus: 'Pull (Back, Rear Delts, Biceps)',
        isRestDay: false,
        exerciseIds: [
          'deadlift-conventional',
          'barbell-bent-over-row',
          'lat-pulldown-wide',
          'cable-face-pulls',
          'barbell-bicep-curl',
          'dumbbell-hammer-curl',
        ],
      },
      3: {
        // Wednesday
        focus: 'Legs & Core (Quads, Hamstrings, Calves)',
        isRestDay: false,
        exerciseIds: [
          'barbell-back-squat',
          'romanian-deadlift',
          'leg-press-45',
          'lying-leg-curl',
          'standing-calf-raises',
          'hanging-leg-raises',
        ],
      },
      4: {
        // Thursday
        focus: 'Push (Hypertrophy & Volume)',
        isRestDay: false,
        exerciseIds: [
          'incline-barbell-bench',
          'chest-dips',
          'cable-lateral-raise',
          'cable-chest-flyes-high',
          'skull-crushers',
        ],
      },
      5: {
        // Friday
        focus: 'Pull (Width & Arms)',
        isRestDay: false,
        exerciseIds: [
          'weighted-pull-ups',
          'seated-cable-row',
          'single-arm-dumbbell-row',
          'rear-delt-pec-deck',
          'incline-dumbbell-curl',
          'preacher-curl',
        ],
      },
      6: {
        // Saturday
        focus: 'Legs & Tactical Conditioning',
        isRestDay: false,
        exerciseIds: [
          'barbell-front-squat',
          'bulgarian-split-squat',
          'seated-leg-curl',
          'farmers-walk',
          'hanging-leg-raises',
        ],
      },
      0: {
        // Sunday
        focus: 'Rest & Full Body Mobility',
        isRestDay: true,
        exerciseIds: ['deep-squat-hold', 'worlds-greatest-stretch', 'dead-hang'],
      },
    },
  },
  {
    id: 'upper-lower-4day',
    name: 'Upper / Lower (4-Day Athletic Split)',
    description:
      'Super efficient 4-day split allowing ample recovery days. Perfect for busy Hunters and athletes.',
    daysPerWeek: 4,
    level: 'Beginner',
    tags: ['Time Efficient', 'Strength', 'Athletic'],
    schedule: {
      1: {
        // Monday
        focus: 'Upper Body Heavy',
        isRestDay: false,
        exerciseIds: [
          'barbell-bench-press',
          'barbell-bent-over-row',
          'overhead-barbell-press',
          'lat-pulldown-wide',
          'barbell-bicep-curl',
          'cable-tricep-pushdown',
        ],
      },
      2: {
        // Tuesday
        focus: 'Lower Body & Core Heavy',
        isRestDay: false,
        exerciseIds: [
          'barbell-back-squat',
          'romanian-deadlift',
          'walking-lunges',
          'standing-calf-raises',
          'ab-wheel-rollout',
        ],
      },
      3: {
        // Wednesday
        focus: 'Rest & Active Recovery',
        isRestDay: true,
        exerciseIds: ['foam-rolling-full', 'dead-hang'],
      },
      4: {
        // Thursday
        focus: 'Upper Body Hypertrophy',
        isRestDay: false,
        exerciseIds: [
          'incline-dumbbell-press',
          'seated-cable-row',
          'standing-dumbbell-lateral-raise',
          'weighted-pull-ups',
          'skull-crushers',
          'dumbbell-hammer-curl',
        ],
      },
      5: {
        // Friday
        focus: 'Lower Body & Conditioning',
        isRestDay: false,
        exerciseIds: [
          'leg-press-45',
          'lying-leg-curl',
          'bulgarian-split-squat',
          'farmers-walk',
          'hanging-leg-raises',
        ],
      },
      6: {
        // Saturday
        focus: 'Cardio / Aerobic Engine',
        isRestDay: false,
        exerciseIds: ['running-outdoor', 'jump-rope-conditioning'],
      },
      0: {
        // Sunday
        focus: 'Rest & Deep Recovery',
        isRestDay: true,
        exerciseIds: ['worlds-greatest-stretch'],
      },
    },
  },
  {
    id: 'bro-split-5day',
    name: 'Classic Bodybuilder Bro Split (5-Day)',
    description:
      'One major muscle group per day. Destroys each muscle with maximum isolated focus.',
    daysPerWeek: 5,
    level: 'Intermediate',
    tags: ['Pump', 'Isolation', 'Classic'],
    schedule: {
      1: {
        // Monday
        focus: 'Chest Annihilation',
        isRestDay: false,
        exerciseIds: [
          'barbell-bench-press',
          'incline-dumbbell-press',
          'chest-dips',
          'cable-chest-flyes-high',
          'push-ups-standard',
        ],
      },
      2: {
        // Tuesday
        focus: 'Back & Lats Width',
        isRestDay: false,
        exerciseIds: [
          'deadlift-conventional',
          'barbell-bent-over-row',
          'lat-pulldown-wide',
          'seated-cable-row',
          'barbell-shrugs',
        ],
      },
      3: {
        // Wednesday
        focus: 'Shoulders & Traps',
        isRestDay: false,
        exerciseIds: [
          'overhead-barbell-press',
          'seated-dumbbell-shoulder-press',
          'standing-dumbbell-lateral-raise',
          'rear-delt-pec-deck',
          'cable-face-pulls',
        ],
      },
      4: {
        // Thursday
        focus: 'Legs (Quads & Hamstrings)',
        isRestDay: false,
        exerciseIds: [
          'barbell-back-squat',
          'leg-press-45',
          'romanian-deadlift',
          'leg-extensions',
          'lying-leg-curl',
          'standing-calf-raises',
        ],
      },
      5: {
        // Friday
        focus: 'Arm Day (Biceps & Triceps)',
        isRestDay: false,
        exerciseIds: [
          'close-grip-bench-press',
          'barbell-bicep-curl',
          'cable-tricep-pushdown',
          'incline-dumbbell-curl',
          'skull-crushers',
          'dumbbell-hammer-curl',
        ],
      },
      6: {
        // Saturday
        focus: 'Cardio & Core Conditioning',
        isRestDay: false,
        exerciseIds: ['treadmill-incline-walk', 'hanging-leg-raises', 'ab-wheel-rollout'],
      },
      0: {
        // Sunday
        focus: 'Rest & Full Recovery',
        isRestDay: true,
        exerciseIds: ['foam-rolling-full'],
      },
    },
  },
  {
    id: 'full-body-3day',
    name: 'Full Body Tactical (3-Day Strength & Conditioning)',
    description:
      'High-impact compound lifts 3 times a week with conditioning days. Great for strength and combat preparedness.',
    daysPerWeek: 3,
    level: 'Beginner',
    tags: ['Functional', 'Strength', 'Conditioning'],
    schedule: {
      1: {
        focus: 'Full Body Heavy A',
        isRestDay: false,
        exerciseIds: [
          'barbell-back-squat',
          'barbell-bench-press',
          'barbell-bent-over-row',
          'hanging-leg-raises',
        ],
      },
      2: {
        focus: 'Active Recovery & Cardio',
        isRestDay: true,
        exerciseIds: ['running-outdoor', 'worlds-greatest-stretch'],
      },
      3: {
        focus: 'Full Body Heavy B',
        isRestDay: false,
        exerciseIds: [
          'deadlift-conventional',
          'overhead-barbell-press',
          'weighted-pull-ups',
          'cable-tricep-pushdown',
        ],
      },
      4: {
        focus: 'Rest & Mobility',
        isRestDay: true,
        exerciseIds: ['dead-hang', 'foam-rolling-full'],
      },
      5: {
        focus: 'Full Body Heavy C',
        isRestDay: false,
        exerciseIds: [
          'front-squats',
          'incline-dumbbell-press',
          'seated-cable-row',
          'barbell-bicep-curl',
          'ab-wheel-rollout',
        ],
      },
      6: {
        focus: 'Conditioning / High Intensity',
        isRestDay: false,
        exerciseIds: ['rowing-machine-erg', 'farmers-walk', 'jump-rope-conditioning'],
      },
      0: {
        focus: 'Full Rest Day',
        isRestDay: true,
        exerciseIds: ['deep-squat-hold'],
      },
    },
  },
];

export function getExerciseById(id: string): ExerciseDefinition | undefined {
  return EXERCISE_LIBRARY.find((e) => e.id === id);
}

export function searchExercises(
  query: string,
  category?: ExerciseCategory | 'All',
  equipment?: ExerciseEquipment | 'All'
): ExerciseDefinition[] {
  const q = query.trim().toLowerCase();
  return EXERCISE_LIBRARY.filter((ex) => {
    const matchesCategory = !category || category === 'All' || ex.category === category;
    const matchesEquipment = !equipment || equipment === 'All' || ex.equipment === equipment;
    const matchesQuery =
      !q ||
      ex.name.toLowerCase().includes(q) ||
      ex.primaryMuscle.toLowerCase().includes(q) ||
      ex.category.toLowerCase().includes(q) ||
      (ex.cue && ex.cue.toLowerCase().includes(q));
    return matchesCategory && matchesEquipment && matchesQuery;
  });
}
